name: Node.js CI

on:
  push:
    branches: 
      - branche_abou
      - main
  pull_request:
    branches:
      - branche_abou
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v2

      - name: Installer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Spécifiez une version LTS de Node.js

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter les tests
        run: npm test
